Feature/swap to express
Cat-1/paw-mailmerge pull request #26
Opened 2024-02-26 03:01 UTC by Cat-1

2024-02-26 04:41 UTC, regular-polygon requested changes
I think we need to remove the auto python app testing GitHub workflow too. It's not passing the check because Test_Backend.py is gone.

2024-02-27 00:43 UTC, Cat-1 commented
I've removed the python workflow from main branch. I had to redo the branch protection rules. Hopefully the settings are right.

2024-03-01 00:11 UTC, regular-polygon requested changes

2024-03-01 00:11 UTC, regular-polygon commented on ReadMe.txt
> +node_modules/forever/bin/forever start index.js
Let's tell users to build the React app before they serve it with express.
after step 1. 
`cd react-paw-mailmerge`
`npm run build`
`cd ..`

2024-03-04 21:46 UTC, regular-polygon approved these changes

2024-03-04 21:46 UTC, merged